services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=flight_booker'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=assalamalaikum'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    ports:
      - '54603:3306'
    volumes:
      - './schema/dump.sql:/docker-entrypoint-initdb.d/schema.sql'